$axure.loadCurrentPage({
  "url":"guide.html",
  "generationDate":new Date(1428503277407.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69348aba4c1a4c9f9a9456a72bc76cd6",
    "type":"Axure:Page",
    "name":"Guide",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"53adc2eb0b5f4276872659d257fae816",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":283,
              "y":28},
            "size":{
              "width":230,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"78184916494946b3b01f01c3bf5dc002",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":952,
              "y":34},
            "size":{
              "width":108,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b7da279a502425b8656f1288cbff236",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":952,
                  "y":34},
                "size":{
                  "width":108,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c971b815c37a47bc8b908a637ae17cbc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":513,
              "y":26.5},
            "size":{
              "width":30,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"006fd92d3f3d4c53ab82ee22abd9f8dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":513,
                  "y":26.5},
                "size":{
                  "width":30,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/foods-添加白萝卜/u106.jpg"}},
{
          "id":"0860d61eaf294a0496afe2d6c2103c65",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":100,
              "y":30},
            "size":{
              "width":160,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b2a42f8bad6458faeacd8b17c24f315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":160,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"576352ebacc94db1bc03857ed9cea4af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":90},
            "size":{
              "width":960,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aa6e5a7875241508bf97a4610444a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":960,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/foods-添加白萝卜/u112.jpg"}},
{
          "id":"d97def1f849a4f86a1740b56ee1b2037",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":539,
              "y":120},
            "size":{
              "width":130,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6374d1828bb041649f21b2e14cff5d67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":539,
                  "y":120},
                "size":{
                  "width":130,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fb5332f62504e72958c93b05ff659d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":100,
              "y":210},
            "size":{
              "width":960,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5f08a5097ba4544925928501e994717",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":210},
                "size":{
                  "width":960,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bc2735542914e3694cbd8dee015314e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "verticalAlignment":"middle",
            "location":{
              "x":576,
              "y":28},
            "size":{
              "width":59,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecb15f31e18e46fa89f703e56631db55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "location":{
                  "x":576,
                  "y":28},
                "size":{
                  "width":59,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 foods-添加白萝卜",
                      "target":{
                        "targetType":"page",
                        "url":"foods-添加白萝卜.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77c05869a5a1479287aa9cc9d472664b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":645,
              "y":32},
            "size":{
              "width":45,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ce46d9f64404128bf0d8cc5110f0b0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":645,
                  "y":32},
                "size":{
                  "width":45,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Guide",
                      "target":{
                        "targetType":"page",
                        "url":"guide.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b793c54d21db41efbe0454ed9bff482a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":710,
              "y":32},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a3bda0fe0364eb29455cef0dec36368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":710,
                  "y":32},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Disclaimer",
                      "target":{
                        "targetType":"page",
                        "url":"disclaimer.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "53adc2eb0b5f4276872659d257fae816":{
      "scriptId":"u0"},
    "78184916494946b3b01f01c3bf5dc002":{
      "scriptId":"u1"},
    "6b7da279a502425b8656f1288cbff236":{
      "scriptId":"u2"},
    "c971b815c37a47bc8b908a637ae17cbc":{
      "scriptId":"u3"},
    "006fd92d3f3d4c53ab82ee22abd9f8dc":{
      "scriptId":"u4"},
    "0860d61eaf294a0496afe2d6c2103c65":{
      "scriptId":"u5"},
    "8b2a42f8bad6458faeacd8b17c24f315":{
      "scriptId":"u6"},
    "576352ebacc94db1bc03857ed9cea4af":{
      "scriptId":"u7"},
    "1aa6e5a7875241508bf97a4610444a90":{
      "scriptId":"u8"},
    "d97def1f849a4f86a1740b56ee1b2037":{
      "scriptId":"u9"},
    "6374d1828bb041649f21b2e14cff5d67":{
      "scriptId":"u10"},
    "8fb5332f62504e72958c93b05ff659d4":{
      "scriptId":"u11"},
    "c5f08a5097ba4544925928501e994717":{
      "scriptId":"u12"},
    "4bc2735542914e3694cbd8dee015314e":{
      "scriptId":"u13"},
    "ecb15f31e18e46fa89f703e56631db55":{
      "scriptId":"u14"},
    "77c05869a5a1479287aa9cc9d472664b":{
      "scriptId":"u15"},
    "8ce46d9f64404128bf0d8cc5110f0b0d":{
      "scriptId":"u16"},
    "b793c54d21db41efbe0454ed9bff482a":{
      "scriptId":"u17"},
    "1a3bda0fe0364eb29455cef0dec36368":{
      "scriptId":"u18"}}});